machine_id: 1
port: 8888
start_time: "2022-05-12"

mysql:
  host: "127.0.0.1"
  port: 3306
  root: "root"
  password: "root"
  db_name: "tiktok"
  max_open_conn: 200
  max_idle_conn: 50

redis:
  host: "127.0.0.1"
  user: "normal"
  password: "123456"
  port: 6379
  db: 0
  pool_size: 100

# 选取合适的AES密钥，可选长度为16、24、32字节
aes:
  key: "just_a_test_key~"

token:
  secret: "just a test key~"